### ISSUE TITLE
エクセプション拾う

### ISSUE THREAD

**Issue by rmanzoku** [rmanzoku/mysql-slowquery-killer#2]
Traceback (most recent call last):
  File "/stpl/apps/mysql-slowquery-killer/mysql-slowquery-killer.py", line 97, in query_killer
    cursor.execute(kill_query)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 217, in execute
    res = self._query(query)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 378, in _query
    rowcount = self._do_query(q)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 341, in _do_query
    db.query(q)
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1094, 'Unknown thread id: 415938108')

**Comment by rmanzoku** [comment]
拾っててログが出てるだけっぽい
